# Generated by Django 4.2.20 on 2025-04-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needs_onboarding',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
